### ISSUE TITLE
Sprite/Image support

### ISSUE THREAD

**Issue by ddaaddaaps** [jdan/isomer#76] opened 2015-05-13 15:28 UTC
I read about that Textures planning support, but I think it 's useful to have support Sprites/Images too, because much people use standard painted art and do not use 3D models.

How do you think?

Sorry for my bad English language, thanks.

**Comment by FabrizioC** [comment] 2015-05-13 15:51
It would be great for me

**Comment by jbovenschen** [comment] 2015-05-13 16:28
Duplicate of #7 so i will close this one.

**Comment by jbovenschen** [comment] 2015-05-13 17:31
Sorry i did not read about the sprites but for me it seems possible with textures and change them every second or so? Right?

**Comment by ddaaddaaps** [comment] 2015-05-13 18:31
No problem. ;-) 

I think Textures isomer make more like to 3D graphics library, like 3D Software Renderers, who most of the time write in 2D Canvas, but with only Isometric projection. And I think then peoples starts write 3D model parsers(.obj, ...) for create something beautiful with isomer. I don't say it is bad. But for Sprites/Images I had to think, when you draw image in Isometric projection and can draw something like:
iso.add(Isomer.Image(new Isomer.Point(x, y z), Something)); and draw you image in x,y,z like Isomer.Prism.
http://fc09.deviantart.net/fs70/f/2011/010/f/0/basic_isometric_tile_set_by_unit_35-d36ukbu.png

Sorry for language, thanks.

**Comment by jbovenschen** [comment] 2015-05-13 22:08
I understand but for such cases you just can create a plane with a texture right and it will just work.

**Comment by ddaaddaaps** [comment] 2015-05-14 06:10
Ah, really, Textures with Planes, now I'm think Textures better to support. Sorry for my little knowledge, thanks and waiting Textures! :-)

**Closed** 2015-05-15 15:41 UTC
